/* empty css                      */import{a as R,S,i as a}from"./assets/vendor-BDlA6vKe.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const p of s.addedNodes)p.tagName==="LINK"&&p.rel==="modulepreload"&&y(p)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function y(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const E="51378857-ce26c557409bd50545eef808f",M="https://pixabay.com/api/",B=15;async function b(r,o=1){return(await R.get(M,{params:{key:E,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:B,page:o}})).data}const m=document.querySelector(".gallery"),l=document.querySelector(".loader"),u=document.querySelector(".load-more");let c=null;function w(r){const o=r.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      </a>
      <div class="info-row">
        <div class="info-block"><span>Likes</span><span>${e.likes}</span></div>
        <div class="info-block"><span>Views</span><span>${e.views}</span></div>
        <div class="info-block"><span>Comments</span><span>${e.comments}</span></div>
        <div class="info-block"><span>Downloads</span><span>${e.downloads}</span></div>
      </div>
    </li>
  `).join("");m.insertAdjacentHTML("beforeend",o),c?c.refresh():c=new S(".gallery a")}function L(){m&&(m.innerHTML="",c&&(c.destroy(),c=null))}function q(){l&&(l.textContent="Loading images, please wait...",l.classList.add("is-visible"))}function f(){l&&(l.textContent="",l.classList.remove("is-visible"))}function g(){u&&u.classList.remove("hidden")}function i(){u&&u.classList.add("hidden")}const P=document.querySelector(".form"),$=P.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let n=1,h="",d=0;const v=15;P.addEventListener("submit",async r=>{r.preventDefault();const o=$.value.trim();if(!o){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}h=o,n=1,L(),i(),q();try{const e=await b(h,n);if(e.hits.length===0){f(),L(),i(),a.info({message:"No results found.",position:"topRight"});return}d=Math.ceil(e.totalHits/v),w(e.hits),e.totalHits>v?g():i()}catch(e){a.error({title:"Error",message:e.message,position:"topRight"})}finally{f()}});x.addEventListener("click",async()=>{console.log("Load More clicked"),n++,n>=d&&i(),i(),q();try{const r=await b(h,n);if(!r.hits||r.hits.length===0){f(),i(),a.info({message:"There are no images matching your search query. Please try again!",position:"topRight"});return}w(r.hits),n<d?g():(i(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}));const o=document.querySelector(".gallery-item");if(!o)return;const{height:e}=o.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(r){a.error({title:"Error",message:r.message,position:"topRight"}),n<d&&g()}finally{f()}});
//# sourceMappingURL=index.js.map
