/* empty css                      */import{a as S,S as R,i as c}from"./assets/vendor-BDlA6vKe.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))h(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&h(m)}).observe(document,{childList:!0,subtree:!0});function e(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function h(t){if(t.ep)return;t.ep=!0;const o=e(t);fetch(t.href,o)}})();const E="51378857-ce26c557409bd50545eef808f",B="https://pixabay.com/api/",M=15;async function b(s,r=1){return(await S.get(B,{params:{key:E,q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:r}})).data}const f=document.querySelector(".gallery"),i=document.querySelector(".loader"),p=document.querySelector(".load-more");let l=new R(".gallery a",{captionsData:"alt",captionDelay:250});function w(s){if(!f)return;const r=s.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      </a>
      <div class="info-row">
        <div class="info-block"><span>Likes</span><span>${e.likes}</span></div>
        <div class="info-block"><span>Views</span><span>${e.views}</span></div>
        <div class="info-block"><span>Comments</span><span>${e.comments}</span></div>
        <div class="info-block"><span>Downloads</span><span>${e.downloads}</span></div>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",r),l.refresh()}function v(){f&&(f.innerHTML="",l&&(l.destroy(),l=null))}function q(){i&&(i.textContent="Loading images, please wait...",i.classList.add("is-visible"))}function y(){i&&(i.textContent="",i.classList.remove("is-visible"))}function d(){p&&p.classList.remove("hidden")}function a(){p&&p.classList.add("hidden")}const P=document.querySelector(".form"),$=P.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let n=1,g="",u=0;const L=15;P.addEventListener("submit",async s=>{s.preventDefault();const r=$.value.trim();if(!r){c.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}g=r,n=1,v(),a(),q();try{const e=await b(g,n);if(e.hits.length===0){y(),v(),a(),c.info({message:"No results found.",position:"topRight"});return}u=Math.ceil(e.totalHits/L),w(e.hits),e.totalHits>L?d():a()}catch(e){c.error({title:"Error",message:e.message,position:"topRight"})}finally{y()}});x.addEventListener("click",async()=>{if(n>=u){a();return}n++,a(),q();try{const s=await b(g,n);w(s.hits),n<u||(a(),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),d();const r=document.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(s){c.error({title:"Error",message:s.message,position:"topRight"}),n<u&&d()}finally{y()}});
//# sourceMappingURL=index.js.map
