/* empty css                      */import{a as R,S,i as a}from"./assets/vendor-BDlA6vKe.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))y(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&y(m)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function y(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const E="51378857-ce26c557409bd50545eef808f",B="https://pixabay.com/api/",M=15;async function b(o,r=1){return(await R.get(B,{params:{key:E,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:M,page:r}})).data}const h=document.querySelector(".gallery"),l=document.querySelector(".loader"),f=document.querySelector(".load-more");let c=null;function w(o){const r=o.map(e=>`
    <li class="gallery-item">
      <a href="${e.largeImageURL}">
        <img src="${e.webformatURL}" alt="${e.tags}" loading="lazy">
      </a>
      <div class="info-row">
        <div class="info-block"><span>Likes</span><span>${e.likes}</span></div>
        <div class="info-block"><span>Views</span><span>${e.views}</span></div>
        <div class="info-block"><span>Comments</span><span>${e.comments}</span></div>
        <div class="info-block"><span>Downloads</span><span>${e.downloads}</span></div>
      </div>
    </li>
  `).join("");h.insertAdjacentHTML("beforeend",r),c?c.refresh():c=new S(".gallery a")}function v(){h&&(h.innerHTML="",c&&(c.destroy(),c=null))}function q(){l&&(l.textContent="Loading images, please wait...",l.classList.add("is-visible"))}function p(){l&&(l.textContent="",l.classList.remove("is-visible"))}function u(){f&&f.classList.remove("hidden")}function i(){f&&f.classList.add("hidden")}const P=document.querySelector(".form"),$=P.querySelector('input[name="search-text"]'),x=document.querySelector(".load-more");let n=1,g="",d=0;const L=15;P.addEventListener("submit",async o=>{o.preventDefault();const r=$.value.trim();if(!r){a.warning({title:"Warning",message:"Please enter a search query.",position:"topRight"});return}g=r,n=1,v(),i(),q();try{const e=await b(g,n);if(e.hits.length===0){p(),v(),i(),a.info({message:"No results found.",position:"topRight"});return}d=Math.ceil(e.totalHits/L),w(e.hits),e.totalHits>L?u():i()}catch(e){a.error({title:"Error",message:e.message,position:"topRight"})}finally{p()}});x.addEventListener("click",async()=>{if(n++,n>=d){i();return}i(),q();try{const o=await b(g,n);if(!o.hits||o.hits.length===0){p(),i(),a.info({message:"There are no images matching your search query. Please try again!",position:"topRight"});return}w(o.hits),n<d||(i(),a.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})),u();const r=document.querySelector(".gallery-item");if(!r)return;const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}catch(o){a.error({title:"Error",message:o.message,position:"topRight"}),n<d&&u()}finally{p()}});
//# sourceMappingURL=index.js.map
